import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const c=window.CFX_CONFIG||{}, sb=c.supabaseUrl&&createClient(c.supabaseUrl,c.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}), jobs=document.getElementById("jobs"), detail=document.getElementById("detail");let refreshInFlight;
const esc=value=>{const e=document.createElement("div");e.textContent=value??"—";return e.innerHTML};
async function getValidAccessToken(){const{data:{session}}=await sb.auth.getSession();if(!session)throw Error("Sign in is required.");if(!session.expires_at||session.expires_at*1000-Date.now()>60000)return session.access_token;refreshInFlight??=sb.auth.refreshSession().finally(()=>{refreshInFlight=null});const{data,error}=await refreshInFlight;if(error||!data.session)throw Error("Your session has expired. Please sign in again.");return data.session.access_token}
async function api(action,body={}){const token=await getValidAccessToken();const r=await fetch(`${c.supabaseUrl.replace(/\/$/,"")}/functions/v1/technician-api`,{method:"POST",headers:{"Content-Type":"application/json",apikey:c.supabaseAnonKey,Authorization:`Bearer ${token}`},body:JSON.stringify({action,...body})}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||"Request failed.");return data}
async function load(){try{const d=await api("dashboard");loginView.hidden=true;portalView.hidden=false;welcome.textContent=`Welcome, ${d.technician.name}`;jobs.innerHTML=`${section("Today's Jobs",d.today)}${section("Upcoming Jobs",d.upcoming)}${section("Completed Jobs",d.completed)}`;document.querySelectorAll(".job").forEach(x=>x.onclick=()=>loadDetail(x.dataset.id))}catch(e){loginError.textContent=e.message}}
function section(title,items){return`<h3 class="h5 mt-3">${title}</h3>${items.length?`<div class="row g-3">${items.map(a=>`<div class="col-12 col-md-6"><button class="job booking-card text-start w-100" data-id="${a.id}"><strong>${esc(a.appointment_id)}</strong><br>${esc(a.customer_name)} · ${esc(a.mobile)}<br>${esc(a.service_category)} ${esc(a.service_type)}<br>${esc(a.appointment_date)} ${esc(a.appointment_time)}<br><span class="badge text-bg-secondary">${esc(a.status)}</span></button></div>`).join("")}</div>`:`<p class="text-muted">None.</p>`}`}
async function loadDetail(id){try{const {appointment:a}=await api("appointment",{id});const map=a.google_maps_url?`<a class="btn btn-outline-primary" target="_blank" rel="noopener" href="${esc(a.google_maps_url)}">Open in Google Maps</a>`:"";detail.innerHTML=`<div class="booking-card"><h2 class="h4">${esc(a.appointment_id)}</h2><p><strong>${esc(a.customer_name)}</strong> · ${esc(a.mobile)}<br>${esc(a.service_category)} ${esc(a.service_type)}<br>${esc(a.appointment_date)} ${esc(a.appointment_time)}<br>${esc(a.service_address)}<br>${esc(a.problem_description)}</p>${map}<hr><p>Current status: <strong>${esc(a.status)}</strong></p><div class="d-flex flex-wrap gap-2"><button class="btn btn-outline-primary action" data-status="on_the_way">Mark On The Way</button><button class="btn btn-outline-primary action" data-status="in_progress">Mark In Progress</button></div><div class="input-group mt-3"><input id="jobCode" class="form-control" value="${esc(a.job_code||"")}" placeholder="CFX-JOB-2026-00452"><button id="saveJob" class="btn btn-outline-primary">Save Job ID</button></div>${["in_progress","job_id_created"].includes(a.status)?`<button id="complete" class="btn btn-success mt-3">${a.status==="job_id_created"?"Complete Job":"Complete Service"}</button><div id="otpArea" class="mt-3"></div>`:""}<p id="techMessage" class="small mt-2"></p></div>`;document.querySelectorAll(".action").forEach(b=>b.onclick=()=>status(id,b.dataset.status));saveJob.onclick=()=>status(id,"job_id_created",jobCode.value);complete?.addEventListener("click",()=>startOtp(id))}catch(e){detail.innerHTML=`<p class="text-danger">${esc(e.message)}</p>`}}
async function status(id,status,job_code){try{await api("set_status",{id,status,job_code});await loadDetail(id);await load()}catch(e){techMessage.textContent=e.message}}
async function startOtp(id){try{await api("start_completion",{id});otpArea.innerHTML=`<div class="alert alert-info">Customer Verification Required. A verification OTP has been sent to the customer's registered email.</div><div class="input-group"><input id="otp" class="form-control" inputmode="numeric" maxlength="6" placeholder="Enter OTP"><button id="verify" class="btn btn-success">Verify & Complete</button></div><button id="resend" class="btn btn-link btn-sm">Resend OTP</button>`;verify.onclick=()=>verifyOtp(id);resend.onclick=()=>startOtp(id)}catch(e){techMessage.textContent=e.message}}
async function verifyOtp(id){try{await api("verify_completion",{id,otp:otp.value});detail.innerHTML=`<div class="alert alert-success">Appointment completed successfully.</div>`;load()}catch(e){techMessage.textContent=e.message}}
signIn.onclick=async()=>{if(!sb)return loginError.textContent="Technician portal is not configured.";const loginEmail=email.value.trim(),loginPassword=password.value;if(!loginEmail||!loginPassword)return loginError.textContent="Enter your technician email and password.";try{const{error}=await sb.auth.signInWithPassword({email:loginEmail,password:loginPassword});if(error)throw error;load()}catch(e){loginError.textContent=e.message}};signOut.onclick=()=>sb.auth.signOut().then(()=>location.reload());if(sb)sb.auth.getSession().then(({data:{session}})=>session&&load());
