(function () {
  const c = window.CFX_CONFIG || {}; const base = (c.supabaseUrl || "").replace(/\/$/, "");
  async function api(name, body) { if (!base || !c.supabaseAnonKey) throw Error("Tracking is not configured."); const r = await fetch(`${base}/functions/v1/${name}`, { method:"POST", headers:{"Content-Type":"application/json",apikey:c.supabaseAnonKey,Authorization:`Bearer ${c.supabaseAnonKey}`}, body:JSON.stringify(body) }); const d = await r.json().catch(()=>({})); if (!r.ok) throw Error(d.error || "Appointment details could not be verified."); return d; }
  const form = document.getElementById("trackingForm");
  if (form) form.onsubmit = async (event) => { event.preventDefault(); const year=document.getElementById("year").value.trim(), code=document.getElementById("code").value.trim(), mobile=document.getElementById("mobile").value.replace(/\D/g,""), error=document.getElementById("trackingError"); error.textContent=""; if (!/^\d{4}$/.test(year)||!/^\d{5}$/.test(code)||!/^[6-9]\d{9}$/.test(mobile)) return void(error.textContent="Enter the year, final five digits, and registered 10-digit mobile number."); try { sessionStorage.setItem("cfx-tracking", JSON.stringify(await api("customer-tracking",{year,code,mobile}))); location.href="../track/"; } catch (x) { error.textContent=x.message; } };
  const out=document.getElementById("trackingResult"); if (!out) return;
  const token=location.pathname.split("/").filter(Boolean).at(-1), request=token&&/^[0-9a-f-]{36}$/i.test(token)?api("customer-tracking",{token}):Promise.resolve(JSON.parse(sessionStorage.getItem("cfx-tracking")||"null")); request.then(render).catch(()=>out.textContent="Appointment details could not be verified.");
  function render(r) { if (!r?.appointment) return void(out.textContent="Appointment details could not be verified."); const a=r.appointment, labels={pending:"Pending",confirmed:"Confirmed",technician_assigned:"Technician Assigned",on_the_way:"On The Way",in_progress:"In Progress",job_id_created:"Job ID Created",completed:"Completed",cancelled:"Cancelled",rescheduled:"Rescheduled",no_show:"No Show"}, h=(r.history||[]).filter(x=>labels[x.new_status]); out.innerHTML=`<h1 class="h3">Appointment Status</h1><p><strong>${esc(a.appointment_id)}</strong></p><p>${esc(a.service)}<br>${esc(a.appointment_date)} · ${esc(a.appointment_time)}<br><span class="badge text-bg-primary">${labels[a.status]}</span></p><h2 class="h5">Timeline</h2><ol>${h.map(x=>`<li><strong>${labels[x.new_status]}</strong> <small>${new Date(x.changed_at).toLocaleString()}</small></li>`).join("")}</ol>${a.job_code?`<div class="alert alert-info"><strong>Job ID Created</strong><br>Job ID: ${esc(a.job_code)}<br><small>For more information, please log in to your Customer Account.</small><br><a class="btn btn-sm btn-primary mt-2" href="https://clickandfix.site/admin/customer-login.html">Visit Customer Portal</a></div>`:""}${a.can_cancel||a.can_reschedule?`<button id="cancel" class="btn btn-outline-danger btn-sm">Cancel appointment</button> <button id="reschedule" class="btn btn-outline-primary btn-sm">Reschedule</button><p id="actionMessage" class="small mt-2"></p>`:""}`; document.getElementById("cancel")?.addEventListener("click",()=>act(a.tracking_token,"cancel")); document.getElementById("reschedule")?.addEventListener("click",()=>{const d=prompt("New date (YYYY-MM-DD)"),t=prompt("New time (HH:MM)");if(d&&t)act(a.tracking_token,"reschedule",d,t);}); }
  async function act(token,action,new_date,new_time) { try { await api("customer-appointment-action",{token,action,new_date,new_time}); location.reload(); } catch (x) { document.getElementById("actionMessage").textContent=x.message; } }
  function esc(v) { const d=document.createElement("div"); d.textContent=v||"—"; return d.innerHTML; }
}());
